#include "images.h"

const ext_img_desc_t images[30] = {
    { "ams", &img_ams },
    { "bell_preview", &img_bell_preview },
    { "encode_preview", &img_encode_preview },
    { "humidity_mockup", &img_humidity_mockup },
    { "humidity", &img_humidity },
    { "nfc_preview", &img_nfc_preview },
    { "power_preview", &img_power_preview },
    { "setting_preview", &img_setting_preview },
    { "spool_base", &img_spool_base },
    { "spool_clean", &img_spool_clean },
    { "spool_fill", &img_spool_fill },
    { "spool_frame", &img_spool_frame },
    { "temperature", &img_temperature },
    { "weight_preview", &img_weight_preview },
    { "logo_28x28_preview", &img_logo_28x28_preview },
    { "spool_mask", &img_spool_mask },
    { "temp_mockup", &img_temp_mockup },
    { "spoolbuddy_logo_light", &img_spoolbuddy_logo_light },
    { "spoolbuddy_logo_transparent", &img_spoolbuddy_logo_transparent },
    { "signal", &img_signal },
    { "nfc", &img_nfc },
    { "ams_setup", &img_ams_setup },
    { "encoding", &img_encoding },
    { "catalog", &img_catalog },
    { "settings", &img_settings },
    { "spoolbuddy_logo_dark", &img_spoolbuddy_logo_dark },
    { "filament_spool", &img_filament_spool },
    { "bell", &img_bell },
    { "dot", &img_dot },
    { "scale", &img_scale },
};
