#include "images.h"

const ext_img_desc_t images[40] = {
    { "humidity", &img_humidity },
    { "spool_base", &img_spool_base },
    { "spool_clean", &img_spool_clean },
    { "spool_fill", &img_spool_fill },
    { "spool_frame", &img_spool_frame },
    { "spool_mask", &img_spool_mask },
    { "spoolbuddy_logo_light", &img_spoolbuddy_logo_light },
    { "signal", &img_signal },
    { "nfc", &img_nfc },
    { "encoding", &img_encoding },
    { "catalog", &img_catalog },
    { "settings", &img_settings },
    { "filament_spool", &img_filament_spool },
    { "bell", &img_bell },
    { "dot", &img_dot },
    { "scale", &img_scale },
    { "amssetup", &img_amssetup },
    { "spool", &img_spool },
    { "spoolbuddy_logo_dark", &img_spoolbuddy_logo_dark },
    { "back", &img_back },
    { "ok", &img_ok },
    { "home", &img_home },
    { "circle_empty", &img_circle_empty },
    { "wifi", &img_wifi },
    { "ip_address", &img_ip_address },
    { "mqtt", &img_mqtt },
    { "add", &img_add },
    { "3d_cube", &img_3d_cube },
    { "scale_2", &img_scale_2 },
    { "display", &img_display },
    { "calibrate", &img_calibrate },
    { "firmware", &img_firmware },
    { "update", &img_update },
    { "reset", &img_reset },
    { "about", &img_about },
    { "thermometer", &img_thermometer },
    { "wifi_signal_1", &img_wifi_signal_1 },
    { "wifi_signal_2", &img_wifi_signal_2 },
    { "wifi_signal_3", &img_wifi_signal_3 },
    { "wifi_signal_4", &img_wifi_signal_4 },
};
